import { Markdown } from 'alem';

const LoadExternalStyles = () => {
   const mdContent = Buffer.from(`IyBMb2FkIEV4dGVybmFsIFN0eWxlcyAtIEZvbnRzICYgQ1NTCgpVc2UgdGhpcyBmZWF0dXJlIHRvIGxvYWQgZXh0ZXJuYWwgZm9udHMgYW5kIGNzcyBmaWxlcyBpbnRvIHlvdXIgYXBwbGljYXRpb24uIChBbGVtIHN1cHBvcnRzIGxvY2FsIC5jc3MgZmlsZXMgdG9vLCBzbyB5b3UgY2FuIGp1c3QgY3JlYXRlIHRoZW0gZnJvbSB0aGUgcHJvamVjdCdzIHJvb3QgZm9sZGVyLikKCmBsb2FkRXh0ZXJuYWxTdHlsZXNgIHJldHVybnMgYSBgYm9vbGVhbmAgaW5mb3JtaW5nIHdoZXRoZXIgYWxsIGNzcyBmaWxlcyBoYXZlIGFscmVhZHkgYmVlbiBsb2FkZWQuCgpZb3UgY2FuIHVzZSBhbnkgZm9udHMgbGlrZSBHb29nbGUgRm9udHMgb3IgQ0ROIEZvbnRzLgoKWW91IG11c3Qgc3BlY2lmeSBgZm9udC1mYW1pbHlgIGluIHRoZSBhcHBsaWNhdGlvbidzIHN0eWxlcy4KCmBgYHRzeAppbXBvcnQgeyBsb2FkRXh0ZXJuYWxTdHlsZXMgfSBmcm9tICJhbGVtIjsKCmNvbnN0IEFwcCA9ICgpID0+IHsKICBjb25zdCBzdHlsZXNMb2FkZWQgPSBsb2FkRXh0ZXJuYWxTdHlsZXMoWwogICAgImh0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20vY3NzMj9mYW1pbHk9T3BlbitTYW5zOml0YWwsd2dodEAwLDMwMC4uODAwOzEsMzAwLi44MDAmZGlzcGxheT1zd2FwIiwKICAgICJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvZ2gvY29kZW1pcnJvci9jb2RlbWlycm9yNS9saWIvY29kZW1pcnJvci5jc3MiLAogIF0pOwoKICBpZiAoIXN0eWxlc0xvYWRlZCkgewogICAgcmV0dXJuIDxwPkxvYWRpbmcuLi48L3A+OwogIH0KCiAgcmV0dXJuIDxwPk15IE5pY2UgQ29udGVudDwvcD47Cn07CgpleHBvcnQgZGVmYXVsdCBBcHA7CmBgYAo=`, "base64").toString("utf-8");
   return <Markdown text={mdContent} />
}

export default LoadExternalStyles;
