import { Markdown } from 'alem';

const Promisify = () => {
   const mdContent = Buffer.from(`IyBQcm9taXNpZnkKClByb21pc2lmeSBpcyB1c2VkIHRvIGNoZWNrIGlmIGEgcGllY2Ugb2YgZGF0YSBpcyBwcmVzZW50IHVudGlsIGEgc3BlY2lmaWMgY2hlY2sgdGltZSBpcyByZWFjaGVkLiBCYXNpY2FsbHkgaXQgY2FsbCByZXNvbHZlIG9yIHJlamVjdCBmb3IgYSBnaXZlbiBjYWxsZXIuCgpUaGlzIHNob3VsZCBvbmx5IGJlIHVzZWQgdG8gb2J0YWluIGRhdGEuIERvIG5vdCB1c2UgaXQgZm9yIHVwZGF0ZXMgYXMgdGhpcyB3aWxsIGdlbmVyYXRlIGEgbG90IG9mIGNhbGxzLgoKYGBgdHMKaW1wb3J0IHsgcHJvbWlzaWZ5IH0gZnJvbSAiYWxlbSI7Cgpjb25zdCBnZXRTdG9yYWdlID0gKCkgPT4gU3RvcmFnZS5nZXQoIm15LWtleSIpOwpjb25zdCByZXNvbHZlID0gKHN0b3JhZ2VEYXRhKSA9PiBjb25zb2xlLmxvZyhzdG9yYWdlRGF0YSk7CmNvbnN0IHJlamVjdCA9ICgpID0+IGNvbnNvbGUubG9nKCJFcnJvciIpOwpjb25zdCB0aW1lb3V0ID0gNTAwMDsgLy8gNXNlYwoKcHJvbWlzaWZ5KGdldFN0b3JhZ2UsIHJlc29sdmUsIHJlamVjdCwgdGltZW91dCk7CmBgYAo=`, "base64").toString("utf-8");
   return <Markdown text={mdContent} />
}

export default Promisify;
