import { Markdown } from 'alem';

const GetLocation = () => {
   const mdContent = Buffer.from(`IyBHZXQgTG9jYXRpb24KClRoaXMgaG9vayByZXR1cm5zIHRoZSBjdXJyZW50IGxvY2F0aW9uIG9iamVjdC4gSXQgY2FuIGJlIHVzZWZ1bCBpZiB5b3UnZCBsaWtlIHRvIHBlcmZvcm0gc29tZSBzaWRlIGVmZmVjdCB3aGVuZXZlciB0aGUgY3VycmVudCBsb2NhdGlvbiBjaGFuZ2VzLgoKVXNlIGBnZXRMb2NhdGlvbigpLmlzUm91dGVzUmVhZHlgIHRvIGdldCB0byBrbm93IHdoZW4gdGhlIHJvdXRlcyBhcmUgcmVhZHkgdG8gYmUgYWNjZXNzZWQuCgpJdCBzaG91bGQgYmUgdXNlZCB3aXRoIGBSb3V0ZXJgLgoKYGBgdHMKLy8gaHR0cDovLzEyNy4wLjAuMTo4MDgwL2FsZW0tbGliLm5lYXIvd2lkZ2V0L0luZGV4P3BhdGg9cHJvZmlsZQppbXBvcnQgeyBnZXRMb2NhdGlvbiB9IGZyb20gImFsZW0iOwoKZXhwb3J0IGNvbnN0IFNvbWVDb21wb25lbnQgPSAoKSA9PiB7CiAgY29uc3QgbG9jYXRpb24gPSBnZXRMb2NhdGlvbigpOwogIGNvbnNvbGUubG9nKGxvY2F0aW9uKTsKICAvLyB7IGlzUm91dGVzUmVhZHk6IHRydWUsIHBhdGhuYW1lOiAicHJvZmlsZSIsIHJvdXRlczogWyJob21lIiwgInByb2ZpbGUiXSB9CgogIHJldHVybiAiIjsKfTsKYGBgCg==`, "base64").toString("utf-8");
   return <Markdown text={mdContent} />
}

export default GetLocation;
