import { Markdown } from 'alem';

const GetLocation = () => {
   const mdContent = Buffer.from(`IyBHZXQgTG9jYXRpb24KClRoaXMgaG9vayByZXR1cm5zIHRoZSBjdXJyZW50IGxvY2F0aW9uIG9iamVjdC4gSXQgY2FuIGJlIHVzZWZ1bCBpZiB5b3UnZCBsaWtlIHRvIHBlcmZvcm0gc29tZSBzaWRlIGVmZmVjdCB3aGVuZXZlciB0aGUgY3VycmVudCBsb2NhdGlvbiBjaGFuZ2VzLgoKVXNlIGBnZXRMb2NhdGlvbigpLmlzUm91dGVzUmVhZHlgIHRvIGdldCB0byBrbm93IHdoZW4gdGhlIHJvdXRlcyBhcmUgcmVhZHkgdG8gYmUgYWNjZXNzZWQuCgpgYGB0cwovLyBodHRwOi8vMTI3LjAuMC4xOjgwODAvYWxlbS1saWIubmVhci93aWRnZXQvSW5kZXg/cGF0aD1wcm9maWxlCmltcG9ydCB7IGdldExvY2F0aW9uIH0gZnJvbSAiYWxlbSI7CgpleHBvcnQgY29uc3QgU29tZUNvbXBvbmVudCA9ICgpID0+IHsKICBjb25zdCBsb2NhdGlvbiA9IGdldExvY2F0aW9uKCk7CiAgY29uc29sZS5sb2cobG9jYXRpb24pOwogIC8vIHsgaXNSb3V0ZXNSZWFkeTogdHJ1ZSwgcGF0aG5hbWU6ICJwcm9maWxlIiwgcm91dGVzOiBbImhvbWUiLCAicHJvZmlsZSJdIH0KCiAgcmV0dXJuICIiOwp9OwpgYGAK`, "base64").toString("utf-8");
   return <Markdown text={mdContent} />
}

export default GetLocation;
