import { Markdown } from 'alem';

const RouteLinkDocs = () => {
   const mdContent = Buffer.from(`IyMgUm91dGUgTGluawoKVGhpcyBjb21wb25lbnQgY3JlYXRlcyBhIGA8YSAvPmAgZWxlbWVudCBhbmQgaXMgdXNlZCB0byBhbGxvdyB1c2VycyB0byBuYXZpZ2F0ZSBiZXR3ZWVuIHJvdXRlcy4gWW91IG11c3QgaW5mb3JtIHRoZSBkZXN0aW5hdGlvbiBwYXRoIHVzaW5nIHRoZSBgdG9gIHByb3BlcnR5LiBJdCBhbHNvIHN1cHBvcnQgYGNsYXNzTmFtZWAsIGBzdHlsZWAgYW5kIGBvbkNsaWNrYCBwcm9wZXJ0aWVzLgoKSXQgc2hvdWxkIGJlIHVzZWQgd2l0aCBgUm91dGVyYC4KCmBgYHRzeAppbXBvcnQgeyBSb3V0ZUxpbmsgfSBmcm9tICJhbGVtIjsKCmV4cG9ydCBjb25zdCBTb21lQ29tcG9uZW50ID0gKCkgPT4gewogIHJldHVybiAoCiAgICA8Um91dGVMaW5rIHRvPSJwcm9maWxlIj4KICAgICAgPHA+R28gdG8gUHJvZmlsZTwvcD4KICAgIDwvUm91dGVMaW5rPgogICk7Cn07CmBgYAo=`, "base64").toString("utf-8");
   return <Markdown text={mdContent} />
}

export default RouteLinkDocs;
