import { Markdown } from 'alem';

const RouteLinkDocs = () => {
   const mdContent = Buffer.from(`IyBSb3V0ZSBMaW5rCgpUaGlzIGNvbXBvbmVudCBjcmVhdGVzIGEgYDxhIC8+YCBlbGVtZW50IGFuZCBpcyB1c2VkIHRvIGFsbG93IHVzZXJzIHRvIG5hdmlnYXRlIGJldHdlZW4gcm91dGVzLiBZb3UgbXVzdCBpbmZvcm0gdGhlIGRlc3RpbmF0aW9uIHBhdGggdXNpbmcgdGhlIGB0b2AgcHJvcGVydHkuIEl0IGFsc28gc3VwcG9ydCBgY2xhc3NOYW1lYCwgYHN0eWxlYCBhbmQgYG9uQ2xpY2tgIHByb3BlcnRpZXMuCgpgUm91dGVMaW5rYCBhY3RzIGRpZmZlcmVudGx5IGRlcGVuZGluZyBvbiB0aGUgYFJvdXRlcmAgY29uZmlndXJhdGlvbi4gSWYgdGhlIFJvdXRlciB0eXBlIGlzIGAiVVJMQmFzZWQiYCwgaXQgd2lsbCBzaW1wbHkgdXNlIHRoZSBuYXRpdmUgYW5jaG9yIGZ1bmN0aW9uIHRvIGdvIHRvIHRoZSBuZXcgVVJMLiBJZiB0aGUgdHlwZSBpcyBgIkNvbnRlbnRCYXNlZCJgIGl0IHdpbGwgY2FsbCB0aGUgUm91dGVyJ3MgYG5hdmlnYXRlYCBmdW5jdGlvbiBhbmQgd2lsbCBkaXNwbGF5IHRoZSBuZXcgcGFnZSB3aXRob3V0IGNhdXNpbmcgYSByZWZyZXNoLCBob3dldmVyLCB0aGUgVVJMIGlzIG5vdCBjaGFuZ2VkLgoKSXQgc2hvdWxkIGJlIHVzZWQgd2l0aCBgUm91dGVyYC4KCmBgYHRzeAppbXBvcnQgeyBSb3V0ZUxpbmsgfSBmcm9tICJhbGVtIjsKCmV4cG9ydCBjb25zdCBTb21lQ29tcG9uZW50ID0gKCkgPT4gewogIHJldHVybiAoCiAgICA8Um91dGVMaW5rIHRvPSJwcm9maWxlIj4KICAgICAgPHA+R28gdG8gUHJvZmlsZTwvcD4KICAgIDwvUm91dGVMaW5rPgogICk7Cn07CmBgYAo=`, "base64").toString("utf-8");
   return <Markdown text={mdContent} />
}

export default RouteLinkDocs;
