import { Markdown } from 'alem';

const BosOverview = () => {
   const mdContent = Buffer.from(`IyBORUFSIEFQSXMgYW5kIENvbXBvbmVudHMKClRoZSBuYXRpdmUgTkVBUiBWTSAoQk9TKSByZXNvdXJjZXMgY29udGludWUgdG8gZnVuY3Rpb24uCgpHZXQgdG8ga25vdyBtb3JlIGFib3V0IHRoZSBCT1MgYnVpbHQgaW4gcmVzb3VyY2VzIGhlcmU6IFtodHRwczovL2RvY3MubmVhci5vcmcvYm9zL2FwaS9zdGF0ZV0oaHR0cHM6Ly9kb2NzLm5lYXIub3JnL2Jvcy9hcGkvc3RhdGUpCgpgYGB0c3gKLy8gTk9URTogVGhlc2UgYXJlIGp1c3QgdGhlIEJPUyBmZWF0dXJlIHJlZmVyZW5jZXMgdHlwZXMKaW1wb3J0IHsKICBGaWxlcywKICBJbmZpbml0ZVNjcm9sbCwKICBJcGZzSW1hZ2VVcGxvYWQsCiAgTWFya2Rvd24sCiAgTmVhciwKICBPdmVybGF5VHJpZ2dlciwKICBTb2NpYWwsCiAgU3RhdGUsCiAgU3RvcmFnZSwKICBUb29sdGlwLAogIFR5cGVBaGVhZCwKICBWTSwKICBXaWRnZXQsCiAgYXN5bmNGZXRjaCwKICBjbGlwYm9hcmQsCiAgY29udGV4dCwKICBmZXRjaCwKICBwcm9wcywKICBzdGF0ZSwKICB1c2VDYWNoZSwKICB1c2VFZmZlY3QsCiAgdXNlU3RhdGUsCiAgdXNlTWVtbywKICBCaWcsCn0gZnJvbSAiYWxlbSI7CgpleHBvcnQgY29uc3QgQ29tcG9uZW50QyA9ICgpID0+IHsKICBjb25zb2xlLmxvZyhwcm9wcyk7IC8vIHdpbGwgcHJpbnQgdGhlIHdpZGdldCBwcm9wcwoKICByZXR1cm4gPENvbXBvbmVudEEgbmFtZT0iV2VuZHoiIC8+Owp9OwpgYGAK`, "base64").toString("utf-8");
   return <Markdown text={mdContent} />
}

export default BosOverview;
