import { Markdown } from 'alem';

const Installation = () => {
   const mdContent = Buffer.from(`IyMgSW5zdGFsbGF0aW9uCgoqKllvdeKAmWxsIG5lZWQgdG8gaGF2ZSBOb2RlIDE4LjAuMCBvciBsYXRlciB2ZXJzaW9uIG9uIHlvdXIgbG9jYWwgZGV2ZWxvcG1lbnQgbWFjaGluZSoqLiBZb3UgY2FuIHVzZSBbbnZtXShodHRwczovL2dpdGh1Yi5jb20vY3JlYXRpb25peC9udm0jaW5zdGFsbGF0aW9uKSAobWFjT1MvTGludXgpIG9yIFtudm0td2luZG93c10oaHR0cHM6Ly9naXRodWIuY29tL2NvcmV5YnV0bGVyL252bS13aW5kb3dzI25vZGUtdmVyc2lvbi1tYW5hZ2VyLW52bS1mb3Itd2luZG93cykgdG8gc3dpdGNoIE5vZGUgdmVyc2lvbnMgYmV0d2VlbiBkaWZmZXJlbnQgcHJvamVjdHMuCgpVc2UgdGhlIGNvbW1hbmQgYmVsb3cgdG8gc3RhcnQgYW4gaW5pdGlhbCBib2lsZXJwbGF0ZS4KCiMjIyBKYXZhU2NyaXB0CgpgYGBzaAojIE5weApucHggY3JlYXRlLWFsZW0tZGFwcCBteS1hcHAKY2QgbXktYXBwCm5wbSBzdGFydApgYGAKCmBgYHNoCiMgWWFybgp5YXJuIGNyZWF0ZSBhbGVtLWRhcHAgbXktYXBwCmNkIG15LWFwcAp5YXJuIHN0YXJ0CmBgYAoKIyMjIFR5cGVTY3JpcHQKCmBgYHNoCiMgTnB4Cm5weCBjcmVhdGUtYWxlbS1kYXBwIG15LWFwcCAtLXRlbXBsYXRlIHR5cGVzY3JpcHQKY2QgbXktYXBwCm5wbSBzdGFydApgYGAKCmBgYHNoCiMgWWFybgp5YXJuIGNyZWF0ZSBhbGVtLWRhcHAgbXktYXBwIC0tdGVtcGxhdGUgdHlwZXNjcmlwdApjZCBteS1hcHAKeWFybiBzdGFydApgYGAK`, "base64").toString("utf-8");
   return <Markdown text={mdContent} />
}

export default Installation;
