name: Deploy DApp to Testnet
on:
  push:
    branches: [staging]
jobs:
  deploy-mainnet:
    uses: wpdas/alem/.github/workflows/deploy-testnet.yml@main
    with:
      signer-account-address: alem-lib.testnet
      signer-public-key: ed25519:8NTXtouT5r4g18XJTErBeqEgDbDXsNxysVgD7DjUnL2N
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.TESTNET_SIGNER_PRIVATE_KEY }}